[package]
name = "chess_engines"
version = "0.1.0"
edition = "2024"

[dependencies]
boxarray = "1.3.1"
chess_core = { version = "0.1.0", path = "../chess_core" }
chrono = "0.4.42"
hashbrown = "0.16.0"
itertools = "0.14.0"
ordered-float = "5.1.0"
rand = "0.9.2"
